<a href="https://colab.research.google.com/github/saiakshitha28-collab/ML_LAB_2026-27/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy is used for numerical calculations.Numpy is imported as np**

In [1]:
import numpy as np

**Numpy Array creation.Array can be created in 1D,2D,3D arrays**

**1D array**

In [3]:
#create list
list=[11, 28, 4, 3]
#create numpy array using list
array = np.array(list)
print(array)

#direst create list in numpy aray
array1=np.array([11, 28, 4, 3])
print(array1)

[11 28  4  3]
[11 28  4  3]


**2D array is created by seperating rows and columns by comma.**

In [4]:
#creating 2D array with 3 rows 4 columns
array2=np.array([[11, 28, 3, 4],[10, 13, 12, 5],[2, 18, 23, 7]])
print(array2)

[[11 28  3  4]
 [10 13 12  5]
 [ 2 18 23  7]]


**3D Array using numpy. It is created using 2d array as slices with rows and columns.**

In [5]:
#create 3D array with 2 slides with 3 rows and 3 columns
array3=np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[10, 11, 12],[13, 14, 15],[16, 17, 18]]])
print(array3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


**Datatype of numpy:** it is checked using "dtype" inbuilt function

In [6]:
print(array.dtype)
print(array1.dtype)
print(array2.dtype)
print(array3.dtype)

int64
int64
int64
int64


**Dimensions of numpy:** it is checked using "ndim" inbuilt function.it checks wheather it is 1D or 2D or 3D array.

In [7]:
print(array.ndim)
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
1
2
3


**Size of numpy array:** it gives no of elements in array. It is used with "size" function.

In [9]:
print(array1.size)
print(array2.size)
print(array3.size)

4
12
18


**Numpy array shape attribute:** In NumPy, the itemsize attribute determines size (in bytes) of each element in the array ie it give the no.of rows and columns in array.it is used with "shape".

In [10]:
print(array1.shape)
print(array2.shape)
print(array3.shape)

(4,)
(3, 4)
(2, 3, 3)


**Numpy array item size attribute:** In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.

In [11]:
array4 = np.array([6, 7, 8, 10, 13], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)
print(array3.itemsize)

print(array4.itemsize)


8
8
8
4


**Numpy array data attribute:** it displays where the array is stored ie memory location.

In [12]:
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)
print("\nData of array3 is: ",array3.data)
print("Data of array4 is: ",array4.data)


Data of array1 is:  <memory at 0x7c025bbb4d00>
Data of array2 is:  <memory at 0x7c025b0eb100>

Data of array3 is:  <memory at 0x7c0294a8ca90>
Data of array4 is:  <memory at 0x7c025bbb4d00>


**Accessing array elements:** elements are accessed using their indexes.

In [13]:
#1D array
print(array1[0])
print(array1[2])

11
4


**Modify Array Elements Using Index**

In [15]:
array1[3] = 23
print(array1)

[11 28  4 23]


**2D array indexing**: elements are accessed using rows and columns ie [1,2] represents element is 1st row and 2nd column.

In [19]:
print(array2[1,3])
print(array3[0,2])

array2[0,2]= 2
print(array2)

5
[7 8 9]
[[11 28  2  4]
 [10 13 12  5]
 [ 2 18 23  7]]


**Numpy statistical Functions:**

median() return the median of an array

mean() return the mean of an array

std() return the standard deviation of an array

percentile() return the nth percentile of elements in an array

min() return the minimum element of an array

max() return the maximum element of an array

these are found using np.mean,np.meadian,np.std,np.percentile,np.min,np.max.



In [20]:
#median
median1 = np.median(array1)
median2 = np.median(array2)
median3 = np.median(array3)
median4 = np.median(array4)
print("Median of array1 is: ",median1)
print("Median of array2 is: ",median2)
print("Median of array3 is: ",median3)
print("Median of array4 is: ",median4)

Median of array1 is:  17.0
Median of array2 is:  10.5
Median of array3 is:  9.5
Median of array4 is:  8.0


In [21]:
#mean
mean1 = np.mean(array1)
mean2= np.mean(array2)
mean3 = np.mean(array3)
mean4 = np.mean(array4)
print("Mean of array1 is: ",mean1)
print("Mean of array2 is: ",mean2)
print("Mean of array3 is: ",mean3)
print("Mean of array4 is: ",mean4)

Mean of array1 is:  16.5
Mean of array2 is:  11.25
Mean of array3 is:  9.5
Mean of array4 is:  8.8


In [22]:
#standard deviation
std1 = np.std(array1)
std2 = np.std(array2)
std3 = np.std(array3)
std4 = np.std(array4)
print("Standard deviation of array1 is: ",std1)
print("Standard deviation of array2 is: ",std2)
print("Standard deviation of array3 is: ",std3)
print("Standard deviation of array4 is: ",std4)

Standard deviation of array1 is:  9.5
Standard deviation of array2 is:  7.907011656329674
Standard deviation of array3 is:  5.188127472091127
Standard deviation of array4 is:  2.481934729198171


In [23]:
#min
min1 = np.min(array1)
min2 = np.min(array2)
min3 = np.min(array3)
min4 = np.min(array)
print("Minimum of array1 is: ",min1)
print("Minimum of array2 is: ",min2)
print("Minimum of array3 is: ",min3)
print("Minimum of array4 is: ",min4)

Minimum of array1 is:  4
Minimum of array2 is:  2
Minimum of array3 is:  1
Minimum of array4 is:  3


In [24]:
#max
max1 = np.max(array1)
max2 = np.max(array2)
max3 = np.max(array3)
max4 = np.max(array4)
print("Maximum of array1 is: ",max1)
print("Maximum of array2 is: ",max2)
print("Maximum of array3 is: ",max3)
print("Maximum of array4 is: ",max4)

Maximum of array1 is:  28
Maximum of array2 is:  28
Maximum of array3 is:  18
Maximum of array4 is:  13


In [27]:
#percentile

percentile1 = np.percentile(array1, 20)
percentile2 = np.percentile(array2, 50)
percentile3 = np.percentile(array3, 65)
percentile4 = np.percentile(array4, 100)

print(percentile1)
print(percentile2)
print(percentile3)
print(percentile4)

8.200000000000001
10.5
12.05
13.0


**Ex: marks of 6 students with 6 rows and 5 columns and applying all statistical functions and operations.**

In [34]:
marks= np.array([[12, 13, 14, 15, 16],[21, 22, 23, 24, 25],[45, 2, 67, 12, 78],[87,45, 23, 67, 12],[13, 45, 35, 87, 66],[87, 45, 23, 77, 98]])
percemtile=np.percentile(marks, 20)
print(marks)
print("Median of marks is: ",np.median(marks))
print("Mean of marks is: ",np.mean(marks))
print("Standard deviation of marks is: ",np.std(marks))
print("Variance of marks is: ",np.var(marks))
print("Minimum of marks is: ",np.min(marks))
print("Maximum of marks is: ",np.max(marks))
print("Percentile")


print(marks[2])

[[12 13 14 15 16]
 [21 22 23 24 25]
 [45  2 67 12 78]
 [87 45 23 67 12]
 [13 45 35 87 66]
 [87 45 23 77 98]]
Median of marks is:  24.5
Mean of marks is:  39.96666666666667
Standard deviation of marks is:  28.417697928501447
Variance of marks is:  807.5655555555554
Minimum of marks is:  2
Maximum of marks is:  98
Percentile
[45  2 67 12 78]
